### ISSUE TITLE
Problems getting 6-3 branch working

### ISSUE THREAD

**Issue by vanthome** [raphendyr/gitlabhq#7]
Hi, I tried the 6-3 now and unfortunately end up with this:

```
(<unknown>): did not find expected key while parsing a block mapping at line 130 column 5 (Psych::SyntaxError)
  /usr/lib64/ruby/2.0.0/psych.rb:205:in `parse'
  /usr/lib64/ruby/2.0.0/psych.rb:205:in `parse_stream'
  /usr/lib64/ruby/2.0.0/psych.rb:153:in `parse'
  /usr/lib64/ruby/2.0.0/psych.rb:129:in `load'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
  /sync1/gitlab/config/initializers/1_settings.rb:47:in `<top (required)>'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:245:in `load'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:245:in `block in load'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:236:in `load_dependency'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:245:in `load'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-3.2.15/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-3.2.15/lib/rails/engine.rb:592:in `each'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-3.2.15/lib/rails/engine.rb:592:in `block in <class:Engine>'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-3.2.15/lib/rails/initializable.rb:30:in `instance_exec'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-3.2.15/lib/rails/initializable.rb:30:in `run'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-3.2.15/lib/rails/initializable.rb:55:in `block in run_initializers'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-3.2.15/lib/rails/initializable.rb:54:in `each'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-3.2.15/lib/rails/initializable.rb:54:in `run_initializers'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-3.2.15/lib/rails/application.rb:136:in `initialize!'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-3.2.15/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /sync1/gitlab/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /sync1/gitlab/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/lib64/ruby/gems/2.0.0/gems/passenger-4.0.23/helper-scripts/rack-preloader.rb:105:in `eval'
  /usr/local/lib64/ruby/gems/2.0.0/gems/passenger-4.0.23/helper-scripts/rack-preloader.rb:105:in `preload_app'
  /usr/local/lib64/ruby/gems/2.0.0/gems/passenger-4.0.23/helper-scripts/rack-preloader.rb:150:in `<module:App>'
  /usr/local/lib64/ruby/gems/2.0.0/gems/passenger-4.0.23/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/local/lib64/ruby/gems/2.0.0/gems/passenger-4.0.23/helper-scripts/rack-preloader.rb:28:in `<main>'
```

Line 130 is the  `enabled: true` in the pam section.
My config looks like this:

```
  #
  #2. Auth settings
  # ==========================

  ## LDAP settings
  ldap:
    enabled: false
    host: '_your_ldap_server'
    base: '_the_base_where_you_search_for_users'
    port: 636
    uid: 'sAMAccountName'
    method: 'ssl' # "ssl" or "plain"
    bind_dn: '_the_full_dn_of_the_user_you_will_bind_with'
    password: '_the_password_of_the_bind_user'
    allow_username_or_email_login: true


  ## PAM settings
  # Currently unix_pam do not work as expected, so pam works only with modules like ldap, sssd, krb
  # or you need to run gitlab as root (NOT RECOMMENDED!)
  # Read more from: https://github.com/canweriotnow/rpam-ruby19/issues/5
  pam:
    enabled: true
    email_domain: 'example.org', # if gecos do not provide email, you need to use this option
    gecos_map: ['name', 'location', 'phone', 'home_phone', 'email'], # map for gecos attributes
    service: 'gitlab', # what pam service to use


  ## OmniAuth settings
  omniauth:
    enabled: true

    # CAUTION!
    # This allows users to login without having a user account first (default: false).
    # User accounts will be created automatically when authentication was successful.
    allow_single_sign_on: false
    # Locks down those users until they have been cleared by the admin (default: true).
    block_auto_created_users: true

    ## Auth providers
    # Uncomment the following lines and fill in the data of the auth provider you want to use
    # If your favorite auth provider is not listed you can use others:
    # see https://github.com/gitlabhq/gitlabhq/wiki/Using-Custom-Omniauth-Providers
    # The 'app_id' and 'app_secret' parameters are always passed as the first two
    # arguments, followed by optional 'args' which can be either a hash or an array.
    providers:
      # - { name: 'google_oauth2', app_id: 'YOUR APP ID',
      #     app_secret: 'YOUR APP SECRET',
      #     args: { access_type: 'offline', approval_prompt: '' } }
      # - { name: 'twitter', app_id: 'YOUR APP ID',
      #     app_secret: 'YOUR APP SECRET'}
      # - { name: 'github', app_id: 'YOUR APP ID',
      #     app_secret: 'YOUR APP SECRET' }
       - { name: 'pam' }
```

**Comment by ab0ris** [comment]
Hi there:)
Don't use commas at the line ends:

```
  ## PAM settings
  # Currently unix_pam do not work as expected, so pam works only with modules like ldap, sssd, krb
  # or you need to run gitlab as root (NOT RECOMMENDED!)
  # Read more from: https://github.com/canweriotnow/rpam-ruby19/issues/5
  pam:
    enabled: true
    email_domain: 'example.org' # if gecos do not provide email, you need to use this option
    gecos_map: ['name', 'location', 'phone', 'home_phone', 'email'] # map for gecos attributes
    service: 'gitlab' # what pam service to use
```

and also do not forget to uncomment line 24 in Gemfile:

```
gem "omniauth-pam", "~> 1.1.0"
```

The 6-3 branch is working fine for me, except one issue #6 I reported yesterday, but it's easy to fix
